name: Merge main to beta

on:
  push:
    branches:
      - main

jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        name: Merge main to beta
        with:
          ref: beta
          fetch-depth: 0
      
      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
      
      - name: Merge main to beta
        run: |
          git branch
          git fetch origin main
          git merge origin/main
          git push origin beta
