name: Manual_choice

on:
  workflow_dispatch:                       # 手動実行イベント
    inputs:
      log-level:
        description: 'Set the logging level' 
        type: choice # 入力パラメータを特定の値に制限
        options:     # 受け付ける入力値を列挙
          - info
          - warn
          - error
          
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - run: echo "${{ inputs.greeting }}" # 入力パラメータ「greeting」の参照
